Add go client
dataspike-io/docver-sdk pull request #13
Opened 2023-09-20 10:48 UTC by ErshovYS

2023-09-20 18:39 UTC, adwells-ds commented
Remove `.idea` please

2023-09-20 18:41 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	GetVerificationByID(string) (*Verification, error)
```suggestion
	GetVerificationByID(UUID) (*Verification, error)
```
`github.com/gofrs/uuid`

2023-09-20 18:41 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	GetApplicant(string) (*Applicant, error)
`UUID`

2023-09-20 18:43 UTC, adwells-ds commented
Please also add short description and link to API documentation for each endpoint

2023-09-20 18:50 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	req.Header = map[string][]string{
Lets avoid creating even more maps on each request
```
req.Header.Set(k,v)
```

2023-09-20 18:52 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	fmt.Println(string(b))
```suggestion

```

2023-09-20 18:56 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +func NewClient(client *http.Client, url, token string) IDataspikeClient {
I suggest to remove `url` from parameters available for end users, it should be internal property, users just can decide, should they use Sandbox or Production client mode

2023-09-20 18:57 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	GetApplicantByExternal(string) (*Applicant, error)
`GetApplicantByExternalID`

2023-09-20 19:40 UTC, narma requested changes

2023-09-20 19:40 UTC, narma commented on go/dataspike/models.go
> +type Residence struct {
```suggestion
type DetailAddress struct {
```

2023-09-21 14:54 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	CancelVerification(string) error
UUID?)

2023-09-21 14:54 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	ProceedVerification(string) error
UUID?)

2023-09-21 14:54 UTC, adwells-ds commented on go/dataspike/dataspike.go
> +	GetApplicantByExternalID(string) (*Applicant, error)
UUID?)

2023-09-25 16:14 UTC, adwells-ds approved these changes

2023-09-26 08:33 UTC, merged